# Change these first
owner: redhcp # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Redhcp
    url: https://www.redhcp.site/

assignees:
  - redhcp
i18n:
  footer: This page is [open source](https://github.com/upptime/upptime)
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Redhcp Status Page
  introTitle: "Welcome to **Redhcp** Status Page"
  introMessage:
  navbar:
    - title: Site
      href: https://www.redhcp.site/
      favicon: https://github.com/redhcp/redhcp.github.io/blob/master/assets/favicon.png
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: light
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
